# Generated by Django 5.0 on 2025-11-04 03:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_map", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landmarkphoto",
            options={"ordering": ["-is_approved", "order", "-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="landmarkphoto",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Upload a photo file",
                null=True,
                upload_to="landmark_photos/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="landmarkphoto",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="landmarkphoto",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="landmarkphoto",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landmarkphoto",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="landmarkphoto",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="PhotoLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_likes",
                        to="campus_map.landmarkphoto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("photo", "user")},
            },
        ),
    ]
