# Generated by Django 5.0 on 2025-11-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campus_map",
            "0002_alter_landmarkphoto_options_landmarkphoto_image_file_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landmarkphoto",
            options={"ordering": ["order", "-uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="landmarkphoto",
            name="image_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="landmark_photos/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="landmarkphoto",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="landmarkphoto",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="PhotoLike",
        ),
    ]
