# Generated by Django 5.0 on 2025-11-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_map', '0003_alter_landmarkphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkphoto',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Photo must be approved by an admin before appearing on the site'),
        ),
    ]
