# Generated by Django 5.0 on 2025-11-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_map', '0004_alter_landmarkphoto_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkphoto',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
